<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAotCompatible>true</IsAotCompatible>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>0.0.3</Version>
    </PropertyGroup>

    <!-- NuGet-related properties -->
    <PropertyGroup>
        <PackageId>carlst99.BinaryPrimitiveHelpers</PackageId>
        <Description>A utility library for reading and writing primitive data in binary representation.</Description>
        <Authors>Carl Stephens</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageOutputPath>$(MSBuildThisFileDirectory)nuget</PackageOutputPath>
        <PackageProjectUrl>https://github.com/carlst99/BinaryPrimitiveHelpers</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>binary binary-primitives</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/carlst99/BinaryPrimitiveHelpers</RepositoryUrl>
    </PropertyGroup>

    <!-- NuGet-related release properties -->
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <!-- Source-link setup -->
    <PropertyGroup>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <!-- Include symbol files (*.pdb) in the built .nupkg. We prefer this to symbol packages as it's a small library (hence restore time minimal) -->
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BinaryPrimitiveHelpers.SourceGeneration\BinaryPrimitiveHelpers.SourceGeneration.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    </ItemGroup>

    <!-- Pack inclusions -->
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)../../README.md">
            <Pack>True</Pack>
            <PackagePath>.</PackagePath>
        </None>
    </ItemGroup>

</Project>
